### ISSUE TITLE
'tupleBatch' object has no attribute 'stores_as'

### ISSUE THREAD

**Issue by shizia** [safe-graph/GNN-FakeNews#10]
When I run the `gnn.py`, in line 156 the error `'tupleBatch' object has no attribute 'stores_as'` occurred. It looks so strange and I don't know why this happen. Could you please tell me how to solve this?

**Comment by YingtongDou** [comment]
This error might be caused by the PyG dataloader. Please make sure you install the latest PyG version correctly. You can run the UPFD [PyG official example](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/upfd.py). If an error still occurs, please report the error to [PyG](https://github.com/pyg-team/pytorch_geometric) project.

**Comment by Yuchen0116** [comment]
I encountered the exact problem in my code! Did you solve the problem with your code? I did install the lastest torch_geometric version, but it still showed that there was an error.

**Comment by YingtongDou** [comment]
@Yuchen0116 You can try to load the dataset using the [pyg official example](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/upfd.py) or install pyg 1.6.1 instead of 2.0+ version.
