### ISSUE TITLE
About eval_helper.py

### ISSUE THREAD

**Issue by Chenzhuomin529** [safe-graph/GNN-FakeNews#12]
After I change data_size = len(loader.dataset.indices()) to data_size = len(loader.dataset.indices) on line 15, I can run the program normally. Otherwise TypeError will be reported: 'list' object is not callable.

**Comment by YingtongDou** [comment]
Do you set `--multi_gpu = True` when you run the GNN models while you only have one GPU?

**Comment by Chenzhuomin529** [comment]
I set --multi_gpu=False when I run the GNN models.

**Comment by YingtongDou** [comment]
What's PyG version are you using?

**Comment by Chenzhuomin529** [comment]
My PyG version is 1.7.0

**Comment by YingtongDou** [comment]
Did you modify the project code? If you modified the code, please send your code to ytongdou@gmail.com and I'll test it on my side.

**Comment by YingtongDou** [comment]
Thanks for sharing your code!

I could run the code with `dataset.indices()` bugfree on my PyCharm but it will report the `'list' object is not callable` error when I test the `dataset.indices()` individually in the terminal. Anyway, I have updated this line to `dataset.indices` in 68d59e7219c400f01eb08928a1cc0eff6a6e6eaf and I will figured out the root cause later.
