### ISSUE TITLE
About the order of feature data

### ISSUE THREAD

**Issue by shizia** [safe-graph/GNN-FakeNews#13]
Hello, sorry to bother you again! I wonder if the four types node feature in the dataset follow the same order from the first node to the last node ? For example , if I want to concatenate the 'spacy' feature and the 'profile' feature, if the same row of these two matrices decribe the same node so that I just need to concatenate the two feature vectors of the same row ? 
Also, even though there is the 'content' feature , it seems that it's different with the concatenation of  'spacy' feature and 'profile' feature when I print them. Is that a problem?
Thanks!

**Comment by YingtongDou** [comment]
Sorry for the late reply.

> I wonder if the four types node feature in the dataset follow the same order from the first node to the last node ?

Yes

> For example , if I want to concatenate the 'spacy' feature and the 'profile' feature, if the same row of these two matrices decribe the same node so that I just need to concatenate the two feature vectors of the same row ?

Yes , you can concatenate the same row since they represent the same user.

> Also, even though there is the 'content' feature , it seems that it's different with the concatenation of 'spacy' feature and 'profile' feature when I print them. Is that a problem?

The `content` feature is composed of a 300-dimensional user **comment** feature and a 10-dimensional user profile feature. The user comment feature is the user reply to current news encoded by spaCy, it is different from the `spacy` feature where we encode a user's recent 200 tweets.
