### ISSUE TITLE
If the news and news publisher feature in dataset

### ISSUE THREAD

**Issue by shizia** [safe-graph/GNN-FakeNews#14]
The content feature is composed of a 300-dimensional user comment feature and a 10-dimensional user profile feature. But it seems that in the code, the first feature of each graph is the news (the root). So is that means the first content feature of each graph is the feature of news and the profile of publisher , not the feature of user comment and user profile?
Also, is the first spacy feature of each graph is the recent 200 news of the publisher?

**Comment by YingtongDou** [comment]
> So is that means the first content feature of each graph is the feature of news and the profile of publisher, not the feature of user comment and user profile?

Yes, the first feature in each graph represents the news encoding plus the profile feature of the Twitter account who first tweets the news.

> Also, is the first spacy feature of each graph is the recent 200 news of the publisher?

The news content feature is only encoded from the current news content, it does not include the historical news since we didn't know the news publisher info.
