### ISSUE TITLE
Bug occurred in utils/eval_helper.py

### ISSUE THREAD

**Issue by shizia** [safe-graph/GNN-FakeNews#9]
Hello! A bug occurred in the utils/eval_helper.py file in the line 15 `data_size = len(loader.dataset.indices())` .
The error is `'list' object is not callable` . I have tried to solve it but I failed .
Could you please tell me why this happen and how to solve? Thanks!

**Comment by YingtongDou** [comment]
It seems that the ``loader`` variable is a ``list`` object instead of ``torch_geometric.loader.dataloader.DataLoader``  object if you set``--multi_gpu = False``.

To fix this bug, please make sure you install the latest PyG version and do not change the original code. If you modify the code, please check the ``loader`` input of the ``eval_deep()`` function has the same type mentioned above.

**Comment by shizia** [comment]
Oh,thanks for your advice , it works now! But there is still a question. It seems that the type of loader `torch_geometric.loader.dataloader.DataLoader` is different from the original code, for the  code of  gnn.py in line 11 is `from torch_geometric.data import DataLoader, DataListLoader` and in 124-127 is 
`if args.multi_gpu:
	loader = DataListLoader
else:
	loader = DataLoader`
I set `multi_gpu = True` and change line 124-127 into `loader=DataLoader`  so that it can work. But if I only set `multi_gpu = True` without changing line 124-127, it can't work . Is there any problem?

**Comment by YingtongDou** [comment]
Do you have multiple GPUs? If you only have one GPU, setting ``multi_gpu = True`` may result in errors.

**Comment by shizia** [comment]
No I don't . If if I only set `multi_gpu = True` without changing the line 124-127, the error is also `'list' object is not callable` .

**Comment by YingtongDou** [comment]
This error might be caused by the PyG dataloader and its multi-GPU integration. Please make sure you install the latest PyG version with correct GPU configurations. You can run the UPFD [PyG official example](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/upfd.py). If an error still occurs, please report the error to [PyG](https://github.com/pyg-team/pytorch_geometric) project.
